<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="89" started-at="2021-06-18T16:33:07 EDT" finished-at="2021-06-18T16:33:07 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="89" started-at="2021-06-18T16:33:07 EDT" finished-at="2021-06-18T16:33:07 EDT">
      <class name="xyz.tamagawa.webcrawler.Main">
        <test-method status="FAIL" signature="fooTestng()[pri:1, instance:xyz.tamagawa.webcrawler.Main@394e1a0f]" name="fooTestng" duration-ms="36" started-at="2021-06-18T16:33:07 EDT" description="first desc is as follows." finished-at="2021-06-18T16:33:07 EDT">
          <exception class="java.lang.ExceptionInInitializerError">
            <full-stacktrace>
              <![CDATA[java.lang.ExceptionInInitializerError
at xyz.tamagawa.utils.BOM.locateBOMs(BOM.java:52)
at xyz.tamagawa.utils.BOM.locateBOMs(BOM.java:42)
at xyz.tamagawa.webcrawler.Main.fooTestng(Main.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IllegalArgumentException: contains illegal character for hexBinary: 0xEFBBBF
at javax.xml.bind.DatatypeConverterImpl.parseHexBinary(DatatypeConverterImpl.java:451)
at javax.xml.bind.DatatypeConverter.parseHexBinary(DatatypeConverter.java:357)
at xyz.tamagawa.utils.BOM$XtdCharset.<init>(BOM.java:34)
at xyz.tamagawa.utils.BOM$XtdCharset.<clinit>(BOM.java:17)
... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ExceptionInInitializerError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fooTestng -->
      </class> <!-- xyz.tamagawa.webcrawler.Main -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
